# Generated by Django 4.2.1 on 2023-06-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_of_course',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='image1_course',
            field=models.ImageField(upload_to='courseimg'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image2_course',
            field=models.ImageField(upload_to='courseimg'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_image',
            field=models.ImageField(upload_to='courseimg'),
        ),
    ]
